### ISSUE TITLE
WMOReader.cs groupFileDataID determination

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/WoWFormatLib#1]
Hi!

In WMOReader you have **groupFileDataID**, which is  determinated using **lodLevel**.

However it is always 0 and never changes in code (never assigned and always used as default 0 value).

_So my question - why ? And if this is correct, why we even have all those conditions for **lodLevel**, which never used?_ 

Because, if it always 0, 
 var start = wmofile.header.nGroups * lodLevel;
var groupFileDataID = wmofile.groupFileDataIDs[start + i]; // will always grab element with index = i;

And in this case how can we be sure **groupFileDataIDs**  will be determined correctly for cases when _groupFileDataIDs count != wmofile.header.nGroup_?

Also, i checked for situations when  groupFileDataIDs count != wmofile.header.nGroup count, those are **always devided by 3** ( groupFileDataIDs  / nGroups  == 3)

Here are examples (nazjatar):

"world/wmo/nazjatar/8nzj_nazjatar_interior01_2400293.wmo"
nGroups = 2                          groupFileDataIDs  = 6

"world/wmo/nazjatar/8nzj_nazjatar_building_small01_2578738.wmo"
nGroups = 3                          groupFileDataIDs  = 9

"world/wmo/nazjatar/8nzj_nazjatar_entrance01_2575951.wmo"
nGroups = 7                          groupFileDataIDs  = 21

"world/wmo/kultiras/human/8hu_kultiras_shiplarge01.wmo"
nGroups = 4                          groupFileDataIDs  = 12

"world/wmo/zuldazar/forsaken/8fk_forsaken_shiplarge01.wmo"
nGroups = 6                          groupFileDataIDs  = 18

And in https://wowdev.wiki/WMO#MOHD_chunk there is something about:

> 03Eh*/  uint16_t numLod;                                         // ≥ Legion (21108) includes base lod (→ numLod = 3 means '.wmo', 'lod0.wmo' and 'lod1.wmo')

Hoping to get your thoughts about this,
Thanks in advance!

**Comment by Marlamin** [comment]
I am genuinely unsure that code works at all, to be honest. I know it works for lod0 but it turns out it won't at all work for Classic for example so it needs to be rewritten regardless. Will probably have a deeper look into what you mentioned when that happens because there's no chance I remember what was going through my head when I wrote that. :D

As for specifically to why it is an option at all, there was a time when one of my applications used it but that's so long ago I don't remember what for.

**Comment by Rokeo** [comment]
btw do you know if it is possible to request model from wow casc (i.e. from server), i found some models missing from current CASC, which used in nazjatar (have it's filedataId)

**Comment by Marlamin** [comment]
If it's not in "current casc" (e.g. root/encoding) and it is the newest build out of all branches then it won't be there for other things either.
