### ISSUE TITLE
Missing chunk handling

### ISSUE THREAD

**Issue by barncastle** [Marlamin/WoWFormatLib#2]
Would it be possible to change the missing chunk handling (e.g. [L136](https://github.com/Marlamin/WoWFormatLib/blob/master/WoWFormatLib/FileReaders/WMOReader.cs#L136)) to a `Console.WriteLine` instead of an exception, or for WoWJsonDumper to cause a soft error instead so new chunks don't break the site?

Also FYI, `MDDI` is a new root WMO chunk.

**Comment by Marlamin** [comment]
That poor utility definitely needs some love, will look at it a bit more and implement this too.
